import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1780171623169 implements MigrationInterface {
    name = 'InitialSchema1780171623169'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."roles_name_enum" AS ENUM('ESTUDIANTE', 'DOCENTE', 'DIRECTOR', 'SOCIEDAD_CIENTIFICA', 'ADMINISTRADOR')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" "public"."roles_name_enum" NOT NULL, "description" character varying(200), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_648e3f5447f725579d7d4ffdfb" ON "roles" ("name") `);
        await queryRunner.query(`CREATE TABLE "student_interests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_profile_id" uuid NOT NULL, "academic_area_id" uuid NOT NULL, "priority" smallint NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_student_interest" UNIQUE ("student_profile_id", "academic_area_id"), CONSTRAINT "chk_student_interest_priority" CHECK (priority >= 1 AND priority <= 5), CONSTRAINT "PK_8e5757dc32afddbf8fc1f61d8bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4101a088bf42022b4c68f5f920" ON "student_interests" ("student_profile_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_386ae46353ccef9141daac674d" ON "student_interests" ("academic_area_id") `);
        await queryRunner.query(`CREATE TABLE "project_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "user_id" uuid NOT NULL, "role_in_project" character varying(80), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_project_member" UNIQUE ("project_id", "user_id"), CONSTRAINT "PK_0b2f46f804be4aea9234c78bcc9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b5729113570c20c7e214cf3f58" ON "project_members" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e89aae80e010c2faa72e6a49ce" ON "project_members" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."project_evidences_type_enum" AS ENUM('link', 'file')`);
        await queryRunner.query(`CREATE TABLE "project_evidences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "type" "public"."project_evidences_type_enum" NOT NULL, "title" character varying(160) NOT NULL, "url" character varying(500) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7bbf96b007655a6187bb121d49d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_343302c16aba87992e012f6944" ON "project_evidences" ("project_id") `);
        await queryRunner.query(`CREATE TYPE "public"."projects_status_enum" AS ENUM('draft', 'active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(160) NOT NULL, "description" text, "status" "public"."projects_status_enum" NOT NULL DEFAULT 'draft', "technologies" text array, "academic_area_id" uuid, "owner_id" uuid NOT NULL, "start_date" date, "end_date" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ec6de185916136cb2fbddd32ff" ON "projects" ("academic_area_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b1bd2fbf5d0ef67319c91acb5c" ON "projects" ("owner_id") `);
        await queryRunner.query(`CREATE TYPE "public"."activity_registrations_status_enum" AS ENUM('interested', 'registered', 'confirmed', 'absent')`);
        await queryRunner.query(`CREATE TABLE "activity_registrations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activity_id" uuid NOT NULL, "student_profile_id" uuid NOT NULL, "status" "public"."activity_registrations_status_enum" NOT NULL DEFAULT 'interested', "confirmed_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_activity_registration" UNIQUE ("activity_id", "student_profile_id"), CONSTRAINT "PK_ed3d336c3b301af02e6f9ffcbd6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bcc386851d4476e5fab2a683c3" ON "activity_registrations" ("activity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b21638a8c330ae083afbfb4a40" ON "activity_registrations" ("student_profile_id") `);
        await queryRunner.query(`CREATE TYPE "public"."activities_type_enum" AS ENUM('academica', 'extracurricular')`);
        await queryRunner.query(`CREATE TYPE "public"."activities_modality_enum" AS ENUM('presencial', 'virtual', 'hibrida')`);
        await queryRunner.query(`CREATE TYPE "public"."activities_status_enum" AS ENUM('draft', 'published', 'open', 'closed', 'finished', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(160) NOT NULL, "description" text, "type" "public"."activities_type_enum" NOT NULL, "modality" "public"."activities_modality_enum" NOT NULL DEFAULT 'presencial', "academic_area_id" uuid, "creator_id" uuid NOT NULL, "event_date" TIMESTAMP WITH TIME ZONE, "capacity" integer, "status" "public"."activities_status_enum" NOT NULL DEFAULT 'draft', "tags" text array, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7f4004429f731ffb9c88eb486a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_704a5fe2080d400189b76938cd" ON "activities" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_b4a09769351466c6567161cf1e" ON "activities" ("academic_area_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f62723d88ccd72e9192bca6292" ON "activities" ("creator_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_146a66975e0a017af25c63c665" ON "activities" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."affinity_results_level_enum" AS ENUM('low', 'medium', 'high')`);
        await queryRunner.query(`CREATE TABLE "affinity_results" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_profile_id" uuid NOT NULL, "academic_area_id" uuid NOT NULL, "score" numeric(6,2) NOT NULL DEFAULT '0', "level" "public"."affinity_results_level_enum" NOT NULL DEFAULT 'low', "calculated_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_affinity_result" UNIQUE ("student_profile_id", "academic_area_id"), CONSTRAINT "PK_e4e853da53e18de9acacf98497b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ee5099d75a475f8543d635f7df" ON "affinity_results" ("student_profile_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9d0079daebb6fa81c5d40faa84" ON "affinity_results" ("academic_area_id") `);
        await queryRunner.query(`CREATE TABLE "academic_areas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(120) NOT NULL, "description" character varying(255), "tags" text array, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9d9d2ebd23be1d08de6afb6ff7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c168bdb675b12baab72abe2c1e" ON "academic_areas" ("name") `);
        await queryRunner.query(`CREATE TABLE "skills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(120) NOT NULL, "academic_area_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0d3212120f4ecedf90864d7e298" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_81f05095507fd84aa2769b4a52" ON "skills" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_60e5eab8ffc315375bc48a973c" ON "skills" ("academic_area_id") `);
        await queryRunner.query(`CREATE TABLE "student_skills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_profile_id" uuid NOT NULL, "skill_id" uuid NOT NULL, "level" smallint NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_student_skill" UNIQUE ("student_profile_id", "skill_id"), CONSTRAINT "chk_student_skill_level" CHECK (level >= 1 AND level <= 5), CONSTRAINT "PK_7bf130eeaf4dcf90221ed38d1a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_22df62931512c384a1ea7c3bad" ON "student_skills" ("student_profile_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_379f5842981fcdc1dc3c886b86" ON "student_skills" ("skill_id") `);
        await queryRunner.query(`CREATE TABLE "external_certificates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_profile_id" uuid NOT NULL, "title" character varying(160) NOT NULL, "issuer" character varying(160) NOT NULL, "url" character varying(500), "issued_date" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d74a6831fb51ac4df715f74497d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5fe0af9cc3f00241eb7d01d1a6" ON "external_certificates" ("student_profile_id") `);
        await queryRunner.query(`CREATE TABLE "internal_constancies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_profile_id" uuid NOT NULL, "title" character varying(160) NOT NULL, "type" character varying(80), "issued_by" uuid NOT NULL, "authorized" boolean NOT NULL DEFAULT true, "issued_date" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ab252a5c2e5df06ad8fdfdff7e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_14cec42ca75fec1519492a4929" ON "internal_constancies" ("student_profile_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_de8827b13bf65606e5840630bc" ON "internal_constancies" ("issued_by") `);
        await queryRunner.query(`CREATE TYPE "public"."student_profiles_status_enum" AS ENUM('incomplete', 'active', 'updated')`);
        await queryRunner.query(`CREATE TABLE "student_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "university_code" character varying(30), "semester" smallint, "bio" text, "status" "public"."student_profiles_status_enum" NOT NULL DEFAULT 'incomplete', "completion_percentage" smallint NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_cef016a0d95e26ae7c0f167ec2" UNIQUE ("user_id"), CONSTRAINT "PK_5ed0a32eeaddfe812fb326177d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cef016a0d95e26ae7c0f167ec2" ON "student_profiles" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7a66baf31b37f3b9301a0e621d" ON "student_profiles" ("university_code") `);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(160) NOT NULL, "password_hash" character varying(255) NOT NULL, "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "role_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_a2cecd1a3531c0b041e29ba46e" ON "users" ("role_id") `);
        await queryRunner.query(`ALTER TABLE "student_interests" ADD CONSTRAINT "FK_4101a088bf42022b4c68f5f9207" FOREIGN KEY ("student_profile_id") REFERENCES "student_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_interests" ADD CONSTRAINT "FK_386ae46353ccef9141daac674d0" FOREIGN KEY ("academic_area_id") REFERENCES "academic_areas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_b5729113570c20c7e214cf3f58d" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_evidences" ADD CONSTRAINT "FK_343302c16aba87992e012f69445" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_ec6de185916136cb2fbddd32ff6" FOREIGN KEY ("academic_area_id") REFERENCES "academic_areas"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_b1bd2fbf5d0ef67319c91acb5cf" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_registrations" ADD CONSTRAINT "FK_bcc386851d4476e5fab2a683c39" FOREIGN KEY ("activity_id") REFERENCES "activities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_registrations" ADD CONSTRAINT "FK_b21638a8c330ae083afbfb4a40b" FOREIGN KEY ("student_profile_id") REFERENCES "student_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_registrations" ADD CONSTRAINT "FK_10fe7a1497ad9c4bccd15b4366a" FOREIGN KEY ("confirmed_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_b4a09769351466c6567161cf1e6" FOREIGN KEY ("academic_area_id") REFERENCES "academic_areas"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_f62723d88ccd72e9192bca62923" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "affinity_results" ADD CONSTRAINT "FK_ee5099d75a475f8543d635f7dfd" FOREIGN KEY ("student_profile_id") REFERENCES "student_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "affinity_results" ADD CONSTRAINT "FK_9d0079daebb6fa81c5d40faa84b" FOREIGN KEY ("academic_area_id") REFERENCES "academic_areas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "FK_60e5eab8ffc315375bc48a973c1" FOREIGN KEY ("academic_area_id") REFERENCES "academic_areas"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_skills" ADD CONSTRAINT "FK_22df62931512c384a1ea7c3bad4" FOREIGN KEY ("student_profile_id") REFERENCES "student_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_skills" ADD CONSTRAINT "FK_379f5842981fcdc1dc3c886b86d" FOREIGN KEY ("skill_id") REFERENCES "skills"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "external_certificates" ADD CONSTRAINT "FK_5fe0af9cc3f00241eb7d01d1a6b" FOREIGN KEY ("student_profile_id") REFERENCES "student_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "internal_constancies" ADD CONSTRAINT "FK_14cec42ca75fec1519492a49291" FOREIGN KEY ("student_profile_id") REFERENCES "student_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "internal_constancies" ADD CONSTRAINT "FK_de8827b13bf65606e5840630bc1" FOREIGN KEY ("issued_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_profiles" ADD CONSTRAINT "FK_cef016a0d95e26ae7c0f167ec28" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "student_profiles" DROP CONSTRAINT "FK_cef016a0d95e26ae7c0f167ec28"`);
        await queryRunner.query(`ALTER TABLE "internal_constancies" DROP CONSTRAINT "FK_de8827b13bf65606e5840630bc1"`);
        await queryRunner.query(`ALTER TABLE "internal_constancies" DROP CONSTRAINT "FK_14cec42ca75fec1519492a49291"`);
        await queryRunner.query(`ALTER TABLE "external_certificates" DROP CONSTRAINT "FK_5fe0af9cc3f00241eb7d01d1a6b"`);
        await queryRunner.query(`ALTER TABLE "student_skills" DROP CONSTRAINT "FK_379f5842981fcdc1dc3c886b86d"`);
        await queryRunner.query(`ALTER TABLE "student_skills" DROP CONSTRAINT "FK_22df62931512c384a1ea7c3bad4"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "FK_60e5eab8ffc315375bc48a973c1"`);
        await queryRunner.query(`ALTER TABLE "affinity_results" DROP CONSTRAINT "FK_9d0079daebb6fa81c5d40faa84b"`);
        await queryRunner.query(`ALTER TABLE "affinity_results" DROP CONSTRAINT "FK_ee5099d75a475f8543d635f7dfd"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_f62723d88ccd72e9192bca62923"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_b4a09769351466c6567161cf1e6"`);
        await queryRunner.query(`ALTER TABLE "activity_registrations" DROP CONSTRAINT "FK_10fe7a1497ad9c4bccd15b4366a"`);
        await queryRunner.query(`ALTER TABLE "activity_registrations" DROP CONSTRAINT "FK_b21638a8c330ae083afbfb4a40b"`);
        await queryRunner.query(`ALTER TABLE "activity_registrations" DROP CONSTRAINT "FK_bcc386851d4476e5fab2a683c39"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_b1bd2fbf5d0ef67319c91acb5cf"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_ec6de185916136cb2fbddd32ff6"`);
        await queryRunner.query(`ALTER TABLE "project_evidences" DROP CONSTRAINT "FK_343302c16aba87992e012f69445"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_b5729113570c20c7e214cf3f58d"`);
        await queryRunner.query(`ALTER TABLE "student_interests" DROP CONSTRAINT "FK_386ae46353ccef9141daac674d0"`);
        await queryRunner.query(`ALTER TABLE "student_interests" DROP CONSTRAINT "FK_4101a088bf42022b4c68f5f9207"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2cecd1a3531c0b041e29ba46e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a66baf31b37f3b9301a0e621d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cef016a0d95e26ae7c0f167ec2"`);
        await queryRunner.query(`DROP TABLE "student_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."student_profiles_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de8827b13bf65606e5840630bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14cec42ca75fec1519492a4929"`);
        await queryRunner.query(`DROP TABLE "internal_constancies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5fe0af9cc3f00241eb7d01d1a6"`);
        await queryRunner.query(`DROP TABLE "external_certificates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_379f5842981fcdc1dc3c886b86"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22df62931512c384a1ea7c3bad"`);
        await queryRunner.query(`DROP TABLE "student_skills"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60e5eab8ffc315375bc48a973c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81f05095507fd84aa2769b4a52"`);
        await queryRunner.query(`DROP TABLE "skills"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c168bdb675b12baab72abe2c1e"`);
        await queryRunner.query(`DROP TABLE "academic_areas"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9d0079daebb6fa81c5d40faa84"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee5099d75a475f8543d635f7df"`);
        await queryRunner.query(`DROP TABLE "affinity_results"`);
        await queryRunner.query(`DROP TYPE "public"."affinity_results_level_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_146a66975e0a017af25c63c665"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f62723d88ccd72e9192bca6292"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4a09769351466c6567161cf1e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_704a5fe2080d400189b76938cd"`);
        await queryRunner.query(`DROP TABLE "activities"`);
        await queryRunner.query(`DROP TYPE "public"."activities_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."activities_modality_enum"`);
        await queryRunner.query(`DROP TYPE "public"."activities_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b21638a8c330ae083afbfb4a40"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bcc386851d4476e5fab2a683c3"`);
        await queryRunner.query(`DROP TABLE "activity_registrations"`);
        await queryRunner.query(`DROP TYPE "public"."activity_registrations_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1bd2fbf5d0ef67319c91acb5c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec6de185916136cb2fbddd32ff"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TYPE "public"."projects_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_343302c16aba87992e012f6944"`);
        await queryRunner.query(`DROP TABLE "project_evidences"`);
        await queryRunner.query(`DROP TYPE "public"."project_evidences_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e89aae80e010c2faa72e6a49ce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5729113570c20c7e214cf3f58"`);
        await queryRunner.query(`DROP TABLE "project_members"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_386ae46353ccef9141daac674d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4101a088bf42022b4c68f5f920"`);
        await queryRunner.query(`DROP TABLE "student_interests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_648e3f5447f725579d7d4ffdfb"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_name_enum"`);
    }

}
